### ISSUE TITLE
I cant not login 

### ISSUE THREAD

**Issue by TheGreatB** [AkashBhave/LocoMoto#1]
am using android studio when i try to sign up it gives me the following errors:

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.akashbhave.locomoto, PID: 21383
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.NullPointerException: lock == null
                      at java.io.Reader.<init>(Reader.java:64)
                      at java.io.InputStreamReader.<init>(InputStreamReader.java:120)
                      at java.io.InputStreamReader.<init>(InputStreamReader.java:57)
                      at io.cloudboost.util.CBParser.inputStreamToString(CBParser.java:317)
                      at io.cloudboost.util.CBParser.callJson(CBParser.java:89)
                      at io.cloudboost.CloudUser.signUp(CloudUser.java:165)
                      at com.akashbhave.locomoto.MainActivity$DownloadTask.doInBackground(MainActivity.java:56)
                      at com.akashbhave.locomoto.MainActivity$DownloadTask.doInBackground(MainActivity.java:39)
                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818) 
E/OpenGLRenderer: SFEffectCache:clear(), mSize = 0
Disconnected from the target VM, address: 'localhost:8600', transport: 'soc

**Comment by TheGreatB** [comment]
Please i need your  help with this solution its urgent!!!!

**Comment by AkashBhave** [comment]
I am looking in to this issue right now.

**Comment by TheGreatB** [comment]
Please do i need the application urgently.. i dont mind paying. thanks

On 27 Dec 2016 08:39, "Akash Bhave" <notifications@github.com> wrote:

I am looking in to this issue right now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AkashBhave/LocoMoto/issues/1#issuecomment-269252093>,
or mute the thread

**Comment by AkashBhave** [comment]
I have fixed the issue. You can now log in and the app correctly connects to CloudBoost (the database service). I believe another issue has arisen in which the map doesn't load, but I believe this can be resolved easily. 

I recommend creating your own CloudBoost account (at https://accounts.cloudboost.io/#/signup) and copying my database set up, so that you using the app doesn't cut into my API calls usage. Just tell me if you want to know exactly how I set up my database.

**Comment by TheGreatB** [comment]
Ok thanks for your immediate response. And yes i would love to know how you setup your database
