### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by TheGreatB** [AkashBhave/LocoMoto#2]
Please how did you setup the database?

**Comment by AkashBhave** [comment]
In my dashboard, I created a new app called "LocoMoto". I then went into the "User" table and added 'location', 'bearing', 'acutalName', and 'role'. I left all the other columns as is because some of them are required, and my app automatically fills them in. Remember to also update the line "CloudApp.init();" with your app keys. 
Below is a screen shot of how I did it.

![database](https://cloud.githubusercontent.com/assets/16819026/21503206/9ee31afe-cc23-11e6-9f5b-5381bd9bba43.PNG)

**Comment by TheGreatB** [comment]
Wow very good explanation. i will dive right into. i will give you a feedback. thanks a lot

**Comment by TheGreatB** [comment]
It is still not able to singn up. i tried using your api keys but no success  then i created the databsase just as you highlighted and addes my own api keys but still not able to signup. i even manually added user details to database (actualName and role).
![loco](https://cloud.githubusercontent.com/assets/21127194/21507427/fc2feec2-cc2c-11e6-8f34-779c300371e5.png)

**Comment by AkashBhave** [comment]
Did it give you an error when you tried to setup? If so, can you show me the Logcat? Make sure you update the line "CloudApp.init()" in "MainActivity". Also, check your database after you login to see if any users were added.

**Comment by TheGreatB** [comment]
Just now i tried using your own API it loggedin then the system crashed. i added my own API after that but the system wont add the user and wont loggin 



12/28 06:03:50: Launching app
$ adb push C:\New folder\LocoMoto-master\LocoMoto-master\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.akashbhave.locomoto
$ adb shell pm install -r "/data/local/tmp/com.akashbhave.locomoto"
	pkg: /data/local/tmp/com.akashbhave.locomoto
Success


$ adb shell am start -n "com.akashbhave.locomoto/com.akashbhave.locomoto.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Connecting to com.akashbhave.locomoto
D/ResourcesManager: creating new AssetManager and set to /data/app/com.akashbhave.locomoto-1/base.apk
W/ActivityThread: Application com.akashbhave.locomoto is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8604', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1369)
I/InstantRun: Instant Run Runtime started. Android package is com.akashbhave.locomoto, real application class is null.
I/GMPM: App measurement is starting up, version: 8487
I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
E/GMPM: Scheduler not set. Not logging error/warn.
E/GMPM: Uploading is not possible. App measurement disabled
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_001.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_002.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_003.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_004.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_005.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_006.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_007.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_008.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_010.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_011.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_012.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_013.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_014.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_000.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_001.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_002.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_003.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_004.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_005.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_006.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_007.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_008.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_010.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_011.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_012.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_013.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_014.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_015.png
V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable/logo.png
D/Activity: performCreate Call secproduct feature valuefalse
D/Activity: performCreate Call debug elastic valuetrue
D/OpenGLRenderer: Render dirty regions requested: true
D/Atlas: Validating map...
V/ActivityThread: updateVisibility : ActivityRecord{1e6519ba token=android.os.BinderProxy@b2c9e4f {com.akashbhave.locomoto/com.akashbhave.locomoto.MainActivity}} show : true
I/OpenGLRenderer: Initialized EGL, version 1.4
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
D/OpenGLRenderer: Enabling debug mode 0

                  [ 12-28 06:05:22.441 10864:11783 E/         ]
                  [android_ws] Format: 5, Width: 1080, Height: 1920


                  [ 12-28 06:05:22.446 10864:11783 E/         ]
                  [android_ws] Format: 5, Width: 1080, Height: 1920


                  [ 12-28 06:05:22.446 10864:11783 E/         ]
                  [android_ws] Format: 5, Width: 1080, Height: 1920


                  [ 12-28 06:05:22.446 10864:11783 E/         ]
                  [android_ws] Format: 5, Width: 1080, Height: 1920
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b2c9e4f time:213211616
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b2c9e4f time:213211617
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
I/GMPM: Tag Manager is not found and thus will not be used
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
I/System.out: driver
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isShipBuild true
I/System.out: (HTTPLog)-Thread-131219-129813534: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
W/System.err: io.cloudboost.CloudException: Invalid column actualName in User
W/System.err:     at io.cloudboost.CloudUser.signUp(CloudUser.java:173)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:63)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:47)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
I/System.out: driver
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
W/System.err: io.cloudboost.CloudException: Invalid column actualName in User
W/System.err:     at io.cloudboost.CloudUser.signUp(CloudUser.java:173)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:63)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:47)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
V/ActivityThread: updateVisibility : ActivityRecord{1e6519ba token=android.os.BinderProxy@b2c9e4f {com.akashbhave.locomoto/com.akashbhave.locomoto.MainActivity}} show : true
W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b2c9e4f time:213289993
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
I/System.out: rider
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
W/System.err: io.cloudboost.CloudException: Invalid column actualName in User
W/System.err:     at io.cloudboost.CloudUser.signUp(CloudUser.java:173)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:63)
W/System.err:     at com.akashbhave.locomoto.MainActivity$DTask.doInBackground(MainActivity.java:47)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by TheGreatB** [comment]
can you figure out what the problem is?

**Comment by AkashBhave** [comment]
I am not really sure what the cause of the problem is. It looks like you are getting the error because of "invalid column actualName in User". The screenshot that you have posted does look correct (actualName is present), but for some reason it is saying it is invalid. I would need to look at your code to help you further. Could you tell me where it is located?

**Comment by TheGreatB** [comment]
i did not edit your code. i redownloaded your code immediately you told me you fiixed the issue. the new problem am facing is when i use your API key i can login with "locoman" but the app crashes upon successful login, my API key is not working moreover i thought "get started" button is suppose to register the a new user and login an existing user. i did not edit your code.

**Comment by AkashBhave** [comment]
Yes, that is what the "Get Started" button is supposed to do. Could you send me the keys to your database so that I can recreate the situation.

**Comment by TheGreatB** [comment]
give me you email so i can send my login details to cloudboost for you to help setup the database?

**Comment by TheGreatB** [comment]
Am still awaiting your response thanks :)

**Comment by rajhaq** [comment]
same here
